# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ClassTest
                                 A QGIS plugin
 my_1st_plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-02
        copyright            : (C) 2018 by mine
        email                :  
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ClassTest class from file ClassTest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .my_1st_plugin_modoule import ClassTest
    return ClassTest(iface)
